###获取当前用户的余额
GET http://127.0.0.1:9001/imooc/ecommerce-account-service/balance/current-balance
Accept: application/json
e-commerce_user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlX3VzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIm1vb2NndWFua2FuZ0AxNjMuY29tXCJ9IiwianRpIjoiYTdhZDA1YzItODRjNC00NzI2LTg3NTMtMjRmZTVhZDFiYTdlIiwiZXhwIjoxNjQ0NTA4ODAwfQ.Yb7FIAm6yzlFCmC77EawrUD8wZ8-MkgK1hTOz_qirY7wfmtFMENESFfe-P_oGRyUnzaD_kUpJw6-hDPNSfsV863J1n0_th0TwLceurnpHCOOTvj8DOGq1bjLvpxhckoWUF0HF1yJN3Qld4CwLucX04cZ_Knu6yxCh6zIocHtr8OiAN_uGQq9kQDBxD80lIZlGOlBMrC65yu10WBr8Se3bUWNVJgsmyP4e5YVOzsvQyOyc80vXpg9NSWJgrv00rLa_EU_mQ04GEvRr6xQkb_smxRCdLWN010FuJRRj_nq1-4YEoBpVzG7rNoGF8d5ptGF5K2bJwXGMoEzuqlp1_iOKA

###扣减用户余额
PUT http://127.0.0.1:9001/imooc/ecommerce-account-service/balance/deduct-balance
Content-Type: application/json
e-commerce_user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlX3VzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIm1vb2NndWFua2FuZ0AxNjMuY29tXCJ9IiwianRpIjoiYTdhZDA1YzItODRjNC00NzI2LTg3NTMtMjRmZTVhZDFiYTdlIiwiZXhwIjoxNjQ0NTA4ODAwfQ.Yb7FIAm6yzlFCmC77EawrUD8wZ8-MkgK1hTOz_qirY7wfmtFMENESFfe-P_oGRyUnzaD_kUpJw6-hDPNSfsV863J1n0_th0TwLceurnpHCOOTvj8DOGq1bjLvpxhckoWUF0HF1yJN3Qld4CwLucX04cZ_Knu6yxCh6zIocHtr8OiAN_uGQq9kQDBxD80lIZlGOlBMrC65yu10WBr8Se3bUWNVJgsmyP4e5YVOzsvQyOyc80vXpg9NSWJgrv00rLa_EU_mQ04GEvRr6xQkb_smxRCdLWN010FuJRRj_nq1-4YEoBpVzG7rNoGF8d5ptGF5K2bJwXGMoEzuqlp1_iOKA

{
  "userId": 10,
  "balance": 1000
}