###查询服务实例信息
GET http://127.0.0.1:8001/ecommerce-nacos-client/nacos-client/service-instance
Accept: application/json

### 查看Sleuth跟踪信息
GET 127.0.0.1:9001/imooc/ecommerce-nacos-client/sleuth/trace-info
Accept: application/json
e-commerce_user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlX3VzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIm1vb2NndWFua2FuZ0AxNjMuY29tXCJ9IiwianRpIjoiNmEwOWVjZGItOTllNC00MjI2LTgwNDYtNjNmMTIyOWVhMWRhIiwiZXhwIjoxNjU5MjgzMjAwfQ.z8L6rALAsDDj8cGQx7DapUZ8fB81WlFAm9mkd6iX9Ho9wpjaSe3oxuTnDAOFQhmq9JCLAdCNjk2MBEzMbrLIFT3WM8WT72jytkDxwuw51abfgbY1QwnWIt1mjvbgM2UBN480hiEBjBGW03YUqUMqEQrgXTZOTk9fY04pJTOJrHAWE167lEnud8HvRFZJeUp_GZUzEfkRxcO0zBSuXuqKba7nvMTKtKN56NQe89A7E3AMdONcrYOmNcPTf6mHrw9BnawTIYrj_SQshEBUj3OQn6j3Zl0f7gYzooL9Ndej96Ruz8PlhMBaEm82WF9GDFdm7CwT_OGLPZdahRRdvrXDog
token: imooc

###
GET 127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce_user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlX3VzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIm1vb2NndWFua2FuZ0AxNjMuY29tXCJ9IiwianRpIjoiZDZhNjBlODktOGUzYi00ZGE3LWE0NzktMjliMmQ3MWM1NTAxIiwiZXhwIjoxNjU5NDU2MDAwfQ.MzgT1p0H5bfEwi9o1njZYOPzxRhhnmYip-xz1ZPluHnn4C8rCi3GdCRG3UGMt8PYvXbKemo_2JbDBVWeYGC8t8nYA1-fJHzLP6AJhuZbO8a9TxTEU7mNsOueWJQMtsbAIkYrLfywQU_XbphfksRRcZjKmJPBiipf6l_x3wlXamY5BICedFZIS35UW7kZr24a4je2jmFWlNFKLb3mAcxhgZEFKtgQVuGE1vbA-iEgwBFKfSWEkR452b9MtUvQk-378SndsgVDUDvQBW4va1D_DiLcZSeJkDecDptHqgqMI1EFpQzD_cVbGQg8sWMVIrvM0i06On2q4AOhaAALNqUyjQ
token: imooc

