### 查询服务
GET 127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce_user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlX3VzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIm1vb2NndWFua2FuZ0AxNjMuY29tXCJ9IiwianRpIjoiMTNkZGU3ZDMtYzgwNy00ZWEyLTgzOWUtODFhY2E4ZGJhYzRhIiwiZXhwIjoxNjU5OTc0NDAwfQ.RVr35szFOYIeoFxqSfTI5poY1ENOwWi_kuZKBlXPSXPfRbrt3ubXNlSxZu5Pmjupwf12apoyGXkGM0Z9dbIPdPRuR0SokjuwXZIZ8Ty7IrOwjC8PTRaQ4gsZzEA1vUdGfGFptpnXcBZ4x39MUd-iSa03rOT9sJ-XwSPLIgr0ltZU4AD45ByQXyT4RMobrYeNR8iUbqTK8iPzsUsXgtNKIcS8O7lDWJrac-ZJFMkpLMeNEqeFG5LI0xViGhNewrVgAbESBrdQUB3oZ2EAEqQxO9QU2cWuss1emnqz5M-2gLmGnRs0uK_cKu8r7V9aNsqvQcjeHLfLtsVdCljsBd83VA
token: imooc