### 查询服务
GET 127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce_user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlX3VzZXIiOiJ7XCJpZFwiOjExLFwidXNlcm5hbWVcIjpcImltb29jZ3VhbmthbmdAMTYzLmNvbVwifSIsImp0aSI6IjQ3MjExOTU1LTYzMTAtNGQxOS04ODRiLTE4YjcyNDY0MDNhYSIsImV4cCI6MTY0MDUzNDQwMH0.sv0MWktkpNaKLnSpvTlQjFamEjDlTtMczH9qyPim7eY3GLUp4gQs2fwy3orSaYdxTyVZ5x84NVbndjduAO3xIwX1pgLnmZ9GhRWfND7DjgeiYsxpQe6X_0MoymD8XKTITVmhjkAaPWqp691X9ekkbd3NYtomBtTPduWA6GpWb4vCQgDdFoNXD5zY29NBoYHSQwyO3FIkRbSPfGxkwkqFAA4gCf6z7EaktcN2mku5DiNUueu_ZUzkgKH0UKfo3OvS7EUJt5uOg5SQ14-AxkIMtUTmzEoCXpn5CW9C39pDuaIoW-LHcyeB8CaKhXO_mNZYWlz5qk2ap6wwJm6MJ5TnNA
token: imooc