### 查询服务
GET 127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce_user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlX3VzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIm1vb2NndWFua2FuZ0AxNjMuY29tXCJ9IiwianRpIjoiY2VlNWViM2UtZTgwOS00NzVmLTgyOTYtZDliZWQxMzE1ZmUxIiwiZXhwIjoxNjQxMDUyODAwfQ.qvKwSW-G5YNT6mrLkSjWCSUjWKu1pS0I7UzcbNqEY2sftnfbvYRgjYu3JnLq95KL0r3u9fNufWITuzm3OxGqSxiEnvGbfh5JZxutCIfzq71SGMy9WsH8Gj-uQ3ZJJFqs7PAn7ItVAIvqc3mgDKeM9o1sjVV7cfGug97_H0hXdDipnHQ1RtYVd0SwxoR2p7xVecldAx7P9UYTleZZCiG9G1fpMRNdPasc3I2iqL1lryJ9G5fnyfjWhm4yFDACAjLVU6AJpHUOmJpFMBpZbpBxgJRy7P8d9WTwNUnBKq_spQbrCoT7zKqKcqR_3hBcPPfXAOAsO04PPSaoUPouuIogDQ
token: imooc